dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe"
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y libsdl2
before_script:
  - ./bootstrap
script:
  - ./configure && make
