language: cpp

env:
  global:
    - NAME=$(grep bin_PROGRAMS src/Makefile.am | cut -d= -f2)

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential xa65 libsdl2-dev
      before_script:
        - ./bootstrap
      script:
        - ./configure && make
        - zip -j $NAME-$TRAVIS_OS_NAME src/$NAME
    - os: osx
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install xa sdl2
      before_script:
        - ./bootstrap
      script:
        - ./configure && make
        - zip -j $NAME-$TRAVIS_OS_NAME src/$NAME
    - os: linux # cross compile to windows
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential mingw-w64 xa65
        - curl -L https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz >SDL2.tar.gz
        - tar xzf SDL2.tar.gz
        - cd SDL2-* && sudo make cross CROSS_PATH=/usr ARCHITECTURES=x86_64-w64-mingw32 && cd -
      script:
        - cd src && make -f Makefile.wingw
        - mkdir epple2 && cp ../epple2.exe /usr/x86_64-w64-mingw32/bin/SDL2.dll ./epple2
        - zip -j $NAME-windows epple2

deploy:
  provider: releases
  file_glob: true
  file: "*.zip"
  skip_cleanup: true
  on:
    tags: true
