dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y libsdl2-2.0 xa65
before_script:
  - ./bootstrap
script:
  - ./configure && make
