language: cpp
compiler:
  - gcc
install: 
  - sudo add-apt-repository --yes ppa:brandontschaefer/sdl-mir-support
  - sudo apt-get install libsdl2
before_script: ./bootstrap
script: ./configure && make
