dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y xa65 libsdl2-2.0 libsdl2-dev libglu1-mesa-dev libglu1-mesa
before_script:
  - ./bootstrap
script:
  - ./configure && make
