dist: xenial
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y xa65 libsdl2-gfx-dev
before_script:
  - ./bootstrap
script:
  - ./configure && make
