language: cpp
compiler:
  - gcc
install: 
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
  - sudo apt-get update
  - sudo apt-get install libsdl2
before_script: ./bootstrap
script: ./configure && make
