language: cpp

env:
  global:
    - NAME=$(grep bin_PROGRAMS src/Makefile.am | cut -d= -f2)

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential xa65 libsdl2-dev
      before_script:
        - ./bootstrap
      script:
        - ./configure && make
        - zip -j $NAME-$TRAVIS_OS_NAME src/$NAME
    - os: osx
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install xa sdl2
      before_script:
        - ./bootstrap
      script:
        - ./configure && make
        - zip -j $NAME-$TRAVIS_OS_NAME src/$NAME
    - os: windows
      before_install:
        - curl -LO https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
        - curl -LO https://www.floodgap.com/retrotech/xa/dists/xa-2.3.9.tar.gz
        - curl -LO https://osdn.net/dl/mingw/mingw-get-0.6.3-mingw32-pre-20170905-1-bin.zip
      install:
        - choco install make
        - 7z x SDL2-devel-2.0.9-VC.zip
        - 7z x xa-2.3.9.tar.gz
        - 7z x xa-2.3.9.tar
        - echo $PATH
        - ls -l '/c/Program Files'
        - ls -l '/c/Program Files (x86)'
        - mkdir mingw-get && cd mingw-get && 7z x ../mingw-get-0.6.3-mingw32-pre-20170905-1-bin.zip && cd ..
        - mingw-get/bin/mingw-get install autotools
      before_script:
        - ./bootstrap
      script:
        - ./configure && make
        - zip -j $NAME-$TRAVIS_OS_NAME src/$NAME

deploy:
  provider: releases
  file_glob: true
  file: "*.zip"
  skip_cleanup: true
  on:
    tags: true
